challenge/unpackaged/objects/DummyProduct__c.object
<CustomObject>
    <fields>
        <fullName>AvailabilityStatus__c</fullName>
        <label>Availability Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Barcode__c</fullName>
        <label>Barcode</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Depth__c</fullName>
        <label>Depth</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DiscountPercentage__c</fullName>
        <label>Discount Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <precision>7</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MinimumOrderQuantity__c</fullName>
        <label>Minimum Order Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>QRCode__c</fullName>
        <label>QR Code</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <precision>3</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ReturnPolicy__c</fullName>
        <label>Return Policy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingInformation__c</fullName>
        <label>Shipping Information</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sku__c</fullName>
        <label>Sku</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stock__c</fullName>
        <label>Stock</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TagsList__c</fullName>
        <label>Tags List</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Thumbnail__c</fullName>
        <label>Thumbnail</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>WarrantyInformation__c</fullName>
        <label>Warranty Information</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <label>Width</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Dummy Product</label>
    <nameField>
        <label>Dummy Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dummy Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

challenge/unpackaged/objects/Product_Image__c.object
<CustomObject>
    <fields>
        <fullName>DummyProduct__c</fullName>
        <label>Dummy Product</label>
        <referenceTo>DummyProduct__c</referenceTo>
        <relationshipLabel>Product Images</relationshipLabel>
        <relationshipName>ProductImages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>ExternalId</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Product Image</label>
    <nameField>
        <label>Product Image Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Images</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

challenge/unpackaged/objects/Review__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>1023</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DummyProduct__c</fullName>
        <description>Product Associated with the Review</description>
        <label>Dummy Product</label>
        <referenceTo>DummyProduct__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>ExternalId</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ReviewerEmail__c</fullName>
        <label>Reviewer Email</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reviewer_Name__c</fullName>
        <label>Reviewer Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Review</label>
    <nameField>
        <label>Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

challenge/unpackaged/classes/productSyncController.cls
public with sharing class productSyncController {

    public class ProductListWrapper {
        public List<ProductWrapper> products;
    }

    public class ProductWrapper {
        public Integer id;
        public String title;
        public String description;
        public String category;
        public Decimal price;
        public Decimal discountPercentage;
        public Decimal rating;
        public Integer stock;
        public List<String> tags;
        public String brand;
        public String sku;
        public Decimal weight;
        public DimensionsWrapper dimensions;
        public String warrantyInformation;
        public String shippingInformation;
        public String availabilityStatus;
        public List<ReviewWrapper> reviews;
        public String returnPolicy;
        public Integer minimumOrderQuantity;
        public MetaWrapper meta;
        public List<String> images;
        public String thumbnail;
    }

    public class DimensionsWrapper {
        public Decimal width;
        public Decimal height;
        public Decimal depth;
    }

    public class MetaWrapper {
        public String barcode;
        public String qrCode;
    }

    public class ReviewWrapper {
        public Integer rating;
        public String comment;
        public String reviewDate; 
        public String reviewerName;
        public String reviewerEmail;
    }
    
    public class LoginResponse {
        public String token;
        public String refreshToken;
        public String id;
        public String username;
    }

    @AuraEnabled
    public static void syncProducts() {
        String accessToken = getAccessToken();
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('callout:DummyJson/products?limit=0');
        request.setMethod('GET');
        request.setHeader('Authorization', 'Bearer ' + accessToken);
        request.setHeader('Accept', 'application/json');
        HttpResponse res = http.send(request);
        
        if (res.getStatusCode() == 200) {
            ProductListWrapper response = (ProductListWrapper) JSON.deserialize(res.getBody(), ProductListWrapper.class);
            List<DummyProduct__c> productsToInsert = new List<DummyProduct__c>();
            List<Review__c> reviewsToInsert = new List<Review__c>();
            List<Product_Image__c> imagesToInsert = new List<Product_Image__c>();

            for (ProductWrapper productInfo : response.products) {
                DummyProduct__c product = new DummyProduct__c();
                product.ExternalId__c = productInfo.id;
                product.Name = productInfo.title;
                product.Description__c = productInfo.description;
                product.Category__c = productInfo.category;
                product.Price__c = productInfo.price;
                product.DiscountPercentage__c = productInfo.discountPercentage;
                product.Rating__c = productInfo.rating;
                product.Stock__c = productInfo.stock;
                product.Brand__c = productInfo.brand;
                product.SKU__c = productInfo.sku;
                product.Weight__c = productInfo.weight;
                product.WarrantyInformation__c = productInfo.warrantyInformation;
                product.ShippingInformation__c = productInfo.shippingInformation;
                product.AvailabilityStatus__c = productInfo.availabilityStatus;
                product.ReturnPolicy__c = productInfo.returnPolicy;
                product.MinimumOrderQuantity__c = productInfo.minimumOrderQuantity;
                product.thumbnail__c = productInfo.thumbnail;
                product.Barcode__c = productInfo.meta != null ? productInfo.meta.barcode : null;
                product.QRCode__c = productInfo.meta != null ? productInfo.meta.qrCode : null;
                product.TagsList__c = productInfo.tags != null ? String.join(productInfo.tags, ';') + ';' : null;

                if (productInfo.dimensions != null) {
                    product.Width__c = productInfo.dimensions.width;
                    product.Height__c = productInfo.dimensions.height;
                    product.Depth__c = productInfo.dimensions.depth;
                }

                productsToInsert.add(product);
            }

            if (!productsToInsert.isEmpty()) {
                upsert productsToInsert ExternalId__c;

                // Link reviews and images after insertion
                for (Integer i = 0; i < productsToInsert.size(); i++) {
                    DummyProduct__c insertedProduct = productsToInsert[i];
                    ProductWrapper productInfo = response.products[i];

                    // Handle reviews
                    if (productInfo.reviews != null) {
                        Integer reviewCounter = 0;
                        for (ReviewWrapper r : productInfo.reviews) {
                            Review__c review = new Review__c();
                            review.ExternalId__c = productInfo.id + 'R' + reviewCounter;
                            review.Name = insertedProduct.Name + r.reviewerName;
                            review.Rating__c = r.rating;
                            review.Comment__c = r.comment;
                            review.Reviewer_Name__c = r.reviewerName;
                            review.ReviewerEmail__c = r.reviewerEmail;
                            review.DummyProduct__c = insertedProduct.Id;

                            try {
                                review.Date__c = !String.isBlank(r.reviewDate) ? DateTime.valueOf(r.reviewDate) : null;
                            } catch (Exception e) {
                                System.debug('Invalid review date: ' + r.reviewDate);
                            }
                            reviewsToInsert.add(review);
                            reviewCounter++;
                        }
                    }

                    // Handle images
                    if (productInfo.images != null) {
                        Integer imageCounter = 0;
                        for (String imageUrl : productInfo.images) {
                            if (String.isNotBlank(imageUrl)) {
                                Product_Image__c image = new Product_Image__c();
                                image.ExternalId__c = productInfo.id + 'I' + imageCounter;
                                image.Name = insertedProduct.Name + ' ' + imageCounter; 
                                image.URL__c = imageUrl;
                                image.DummyProduct__c = insertedProduct.Id;
                                imagesToInsert.add(image);
                            }
                            imageCounter++;
                        }    
                    }
                }

                if (!reviewsToInsert.isEmpty()) upsert reviewsToInsert ExternalId__c;
                if (!imagesToInsert.isEmpty()) upsert imagesToInsert ExternalId__c;
            }
        } else {
            System.debug('Failed to fetch products: ' + res.getStatusCode() + ' - ' + res.getBody());
        }
    }

    // Public method to get the access token
    public static String getAccessToken() {
        
        // Access login credentials
        String username = 'emilys';
        String password = 'emilyspass';

        /* DummyJSON_Secrets__c creds = DummyJSON_Secrets__c.getInstance();
        String username = creds.Username__c;
        String password = creds.Password__c; */

        //Post request to login to the server
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('callout:DummyJson/auth/login');
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json');
        request.setHeader('Accept', 'application/json');
        request.setBody('{' +
            '"username": "' + username + '",' +
            '"password": "' + password +'",' +
            '"expiresInMins": 60' +
        '}');

        HttpResponse response = http.send(request);

        if (response.getStatusCode() == 200) {
            LoginResponse login = (LoginResponse) JSON.deserialize(response.getBody(), LoginResponse.class);

            return login.token;
        } else {
            throw new CalloutException('Login failed: ' + response.getBody());
        }
    }
}